version: '3.7'
services:
 nodeapp:
  image: appimg
  ports: 
  - target: 5656
    published: 80
    protocol: tcp
  build:
   context: .
  deploy:
   replicas: 3
   labels:
   - "com.nodeapp=service with nodeapp containers"
